\open Nat (+)

\func test1 => (<weak_warning descr="Redundant parentheses">(1 + 2)</weak_warning> : Nat, <weak_warning descr="Redundant parentheses">(3 + 4)</weak_warning>)

\func f {A : \Type} => 1
\func test2 => f {<weak_warning descr="Redundant parentheses">(1 = 1)</weak_warning> : <weak_warning descr="Redundant parentheses">(\Type 0)</weak_warning>}

\func test3 : \Sigma (0 = 1 -> Nat) Nat => ((\case __), 2)
\func test4 : \Sigma (0 = 1 -> Nat) Nat => (<weak_warning descr="Redundant parentheses">(\case __ \with {})</weak_warning>, 2)
\func test5 : \Sigma (0 = 1 -> Nat) Nat => (<weak_warning descr="Redundant parentheses">(\case __ \return Nat)</weak_warning>, 2)