{
    parserClass = "org.vclang.lang.parser.VclParser"

    elementTypeHolderClass = "org.vclang.vclpsi.VclElementTypes"

    elementTypeClass = "org.vclang.vclpsi.VclElementType"
    tokenTypeClass = "org.vclang.vclpsi.VclTokenType"

    psiClassPrefix = "Vcl"
    psiImplClassSuffix = "Impl"
    psiPackage = "org.vclang.vclpsi"
    psiImplPackage = "org.vclang.vclpsi.impl"
    generateTokenAccessors = true

    tokens = [
        DEPS = "dependencies"
        SOURCE = "sourcesDir"
        BINARY = "binariesDir"
        MODULES = "modules"
        COLON = ":"
    ]

}

statements ::= statement*

statement ::= deps_st | source_st | binary_st | modules_st

deps_st ::= DEPS COLON LIBNAME*
source_st ::= SOURCE COLON DIRNAME
binary_st ::= BINARY COLON DIRNAME
modules_st ::= MODULES COLON MODNAME*
