{
    parserClass = "org.vclang.parser.VclParser"

    elementTypeHolderClass = "org.vclang.vclpsi.VclElementTypes"

    elementTypeClass = "org.vclang.vclpsi.VclElementType"
    tokenTypeClass = "org.vclang.vclpsi.VclTokenType"

    psiClassPrefix = "Vcl"
    psiImplClassSuffix = "Impl"
    psiPackage = "org.vclang.vclpsi"
    psiImplPackage = "org.vclang.vclpsi.impl"
    generateTokenAccessors = true

    tokens = [
        DEPS = "dependencies"
        SOURCE = "sourcesDir"
        BINARY = "binariesDir"
        MODULES = "modules"
        COLON = ":"
        ID = "ID"

        BLOCK_COMMENT_START = '{-'
        BLOCK_COMMENT_END   = '-}'
        LINE_COMMENT        = "regexp:--[^\r\n]*"
        BLOCK_COMMENT       = '{- BLOCK_COMMENT -}'
    ]

}

statements ::= (!<<eof>> statement)*

statement ::= depsStat | sourceStat | binaryStat | modulesStat

depsStat ::= DEPS COLON libName* {
    pin = 1
}

sourceStat ::= SOURCE COLON DIRECTORY_NAME {
    pin = 1
}

binaryStat ::= BINARY COLON DIRECTORY_NAME {
    pin = 1
}

modulesStat ::= MODULES COLON modName* {
    pin = 1
}

libName ::= LIBRARY_NAME

modName ::= MODULE_NAME
