name: check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    env:
      NO_FS_ROOTS_ACCESS_CHECK: true
    steps:
    - uses: actions/checkout@v2
      with:
        path: intellij-arend
    - uses: actions/checkout@v2
      with:
        repository: JetBrains/Arend
        path: Arend
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: eskatos/gradle-command-action@v1
      with:
        wrapper-cache-enabled: false
        cache-disabled: true
        build-root-directory: intellij-arend
        wrapper-directory: intellij-arend
        arguments: clean test --info --no-daemon --stacktrace
    - uses: eskatos/gradle-command-action@v1
      # Normally, macOS runs faster than the other two
      if: matrix.os == 'macOS-latest' && matrix.java == '17'
      with:
        wrapper-cache-enabled: false
        cache-disabled: true
        build-root-directory: intellij-arend
        wrapper-directory: intellij-arend
        arguments: assemble --info --no-daemon --stacktrace
    - uses: actions/upload-artifact@master
      if: matrix.os == 'macOS-latest' && matrix.java == '17'
      with:
        name: Plugin
        path: intellij-arend/build/distributions
